version: "3.8"
services:
  db:
    image: postgres:16
    container_name: task-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task-management
    ports:
      - "5433:5432"

  grafana:
    image: grafana/grafana
    container_name: task-management-grafana
    restart: unless-stopped
    environment:
      GF_LOG_LEVEL: debug
    ports:
      - "3001:3000"
