version: "3.8"
services:
  db:
    image: postgres:16
    container_name: task-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schola
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: task-management-grafana
    restart: unless-stopped
    environment:
      GF_LOG_LEVEL: debug
    ports:
      - "3001:3000"

volumes:
  db_data:
